version: "3.9"

services:

  db:
    image: mysql:8.2
    container_name: rabit_microservice_db
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - dbdata:/var/lib/mysql
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - laravel


  api_gateway_app:
    build:
      context: ./rabit_api_gateway
      dockerfile: docker/php/Dockerfile
    container_name: api_gateway_app
    restart: always
    volumes:
      - .:/var/www
      - /var/www/rabit_api_gateway/vendor
    depends_on:
      - db
    networks:
      - laravel

  auth_app:
    build:
      context: ./rabit_auth
      dockerfile: docker/php/Dockerfile
    container_name: auth_app
    restart: always
    volumes:
      - .:/var/www
      - /var/www/rabit_auth/vendor
    depends_on:
      - db
    networks:
      - laravel

  carts_app:
    build:
      context: ./rabit_carts
      dockerfile: docker/php/Dockerfile
    container_name: carts_app
    restart: always
    volumes:
      - .:/var/www
      - /var/www/rabit_carts/vendor
    depends_on:
      - db
    networks:
      - laravel

  products_app:
    build:
      context: ./rabit_products
      dockerfile: docker/php/Dockerfile
    container_name: products_app
    restart: always
    volumes:
      - .:/var/www
      - /var/www/rabit_products/vendor
    depends_on:
      - db
    networks:
      - laravel

  orders_app:
    build:
      context: ./rabit_orders
      dockerfile: docker/php/Dockerfile
    container_name: orders_app
    restart: always
    volumes:
      - .:/var/www
      - /var/www/rabit_orders/vendor
    depends_on:
      - db
    networks:
      - laravel




  api_gateway_web:
    image: nginx:latest
    container_name: gateway_web
    restart: always
    ports:
      - "8000:80"
    volumes:
      - .:/var/www
      - ./rabit_api_gateway/docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - api_gateway_app
    networks:
      - laravel

  auth_web:
    image: nginx:latest
    container_name: auth_web
    restart: always
    ports:
      - "8001:80"
    volumes:
      - .:/var/www
      - ./rabit_auth/docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - auth_app
    networks:
      - laravel

  carts_web:
    image: nginx:latest
    container_name: carts_web
    restart: always
    ports:
      - "8002:80"
    volumes:
      - .:/var/www
      - ./rabit_carts/docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - carts_app
    networks:
      - laravel

  products_web:
    image: nginx:latest
    container_name: products_web
    restart: always
    ports:
      - "8003:80"
    volumes:
      - .:/var/www
      - ./rabit_products/docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - products_app
    networks:
      - laravel

  orders_web:
    image: nginx:latest
    container_name: orders_web
    restart: always
    ports:
      - "8004:80"
    volumes:
      - .:/var/www
      - ./rabit_orders/docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - orders_app
    networks:
      - laravel

networks:
  laravel:

volumes:
  dbdata:
